"""Catalog-generation figures.

The five paper figures that describe the catalog itself, ported from
`load_stars.ipynb`, `sim_planets.ipynb`, and `analysis/schematic_figure.ipynb`:

    star_sky_scanlaw_<frame>     parent sample over the DR4 scan law
    population_schematic         selection funnel + population branching
    pop_diagnostics_1planet      one-companion prior distributions
    pop_diagnostics_2planet      two-companion prior distributions
    companion_gallery            sample on-sky orbits, one row per population
    simulated_planets_mass_period  mass vs. period, coloured by signature alpha

The later analysis figures (characterizability maps, the LW25 comparison) stay
in `analysis/`, since they need the periodogram characterization rather than the
catalog alone.

Colours, sizes, and formats are module constants in `config.py`; annotations
that quote numbers (sample counts, prior ranges) are read from the config and
the catalog on disk, so they cannot drift away from what was actually run.

The figures are unchanged from the serial pipeline, including the random vs
high-SNR comparisons. What changed is where the high-SNR sample comes from: it
is no longer generated by rejection sampling but selected after the fact as the
rows of a random population whose every companion clears `HIGH_SNR_MIN`. Every
figure reads through `read_population(name, high_snr=...)`, which applies that
cut and maps the sharded truth schema onto the column names the figures use.
"""

from __future__ import annotations

from functools import lru_cache

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

from . import config as C
from .sources import select_high_snr


def _apply_style():
    """Global typography for every figure in this module."""
    matplotlib.rc("xtick", labelsize=18)
    matplotlib.rc("ytick", labelsize=18)
    matplotlib.rc("font", **{"family": C.FONT_FAMILY, "serif": [C.SERIF_FONT]})
    matplotlib.rc("text", usetex=C.USETEX)


def _save(fig, stem):
    """Write one figure in every configured format; returns the paths."""
    C.figure_dir().mkdir(parents=True, exist_ok=True)
    written = []
    for suffix in C.FORMATS:
        path = C.figure_dir() / f"{stem}.{suffix}"
        if suffix == "png":
            fig.savefig(path, bbox_inches="tight", dpi=C.PNG_DPI)
        else:
            fig.savefig(path, bbox_inches="tight")
        written.append(path)
    print(f"  wrote {', '.join(str(p) for p in written)}")
    plt.close(fig)
    return written


def read_population(population, high_snr=False):
    """See `_read_population`; this only normalizes the cache key.

    `lru_cache` keys on the argument tuple, so `read_population(p)` and
    `read_population(p, False)` would otherwise be two entries -- and the
    figures call it both ways.
    """
    return _read_population(population, bool(high_snr))


@lru_cache(maxsize=None)
def _read_population(population, high_snr):
    """A population as a DataFrame, in the column names the figures expect.

    Reads the merged truth table (or the shard files) and renames the sharded
    schema back to the legacy figure columns: `sma_1 -> sma` for one-companion
    populations, `alpha_mas_k -> alpha_k_mas`, `mass_st_msun -> mass_st`,
    `parallax_mas -> parallax`.

    Cached: a full figure set asks for the same four tables sixteen times, and
    at 4M systems each one is a GB-scale parquet decode. The figures only ever
    read the frames, never mutate them, so one copy is shared.

    For a high-SNR view this prefers the table the `select` stage already wrote
    -- 1% of the rows -- and only falls back to recomputing the cut if that file
    is absent.
    """
    if high_snr:
        selected = C.truths(population, high_snr=True)
        if selected.exists():
            frame = pd.read_parquet(selected)
        else:
            frame = select_high_snr(_read_population(population, False))
    else:
        merged = C.truths(population)
        if merged.exists():
            frame = pd.read_parquet(merged)
        else:
            parts = sorted(C.shard_dir(population).glob("truths_*.parquet"))
            if not parts:
                raise FileNotFoundError(
                    f"no truth table for {population}: neither {merged} nor shards "
                    f"in {C.shard_dir(population)}"
                )
            frame = pd.concat([pd.read_parquet(p) for p in parts], ignore_index=True)

    frame = frame.rename(
        columns={
            "mass_st_msun": "mass_st",
            "parallax_mas": "parallax",
            "mass_interp": "mass_st",
        }
    )
    for k in (1, 2):
        if f"alpha_mas_{k}" in frame.columns:
            frame = frame.rename(columns={f"alpha_mas_{k}": f"alpha_{k}_mas"})
    if C.POPULATIONS[population] == 1:
        frame = frame.rename(
            columns={
                c: c[:-2]
                for c in frame.columns
                if c.endswith("_1") and c != "alpha_1_mas"
            }
        )
        frame = frame.rename(columns={"alpha_1_mas": "alpha_mas"})
    return frame


# ==========================================================================
# 1. Parent sample over the DR4 scan law
# ==========================================================================
def add_curved_colorbar(
    ax,
    vmin,
    vmax,
    cmap,
    *,
    side="top",
    half_angle=20.0,
    r_in=1.03,
    r_out=1.07,
    nseg=256,
    ticks=None,
    label="",
    fontsize=10,
    text_color="k",
    edge_color="k",
):
    """Colorbar drawn as an annular arc hugging the top or bottom of a healpy
    Mollweide ellipse.

    healpy draws the ellipse as (2 cos t, sin t) in axes data coordinates; the
    band lives between scaled ellipses r_in and r_out over
    t = centre +/- half_angle, with values running vmin (left) -> vmax (right).
    Call after `hp.mollview`, on the healpy axes.
    """
    from matplotlib.collections import PolyCollection

    cmap = plt.get_cmap(cmap) if isinstance(cmap, str) else cmap
    top = side == "top"
    centre = 90.0 if top else -90.0

    t0 = np.radians(centre + (half_angle if top else -half_angle))  # vmin end
    t1 = np.radians(centre - (half_angle if top else -half_angle))  # vmax end
    t = np.linspace(t0, t1, nseg + 1)

    xi, yi = 2.0 * r_in * np.cos(t), r_in * np.sin(t)
    xo, yo = 2.0 * r_out * np.cos(t), r_out * np.sin(t)

    verts = [
        [(xi[i], yi[i]), (xi[i + 1], yi[i + 1]), (xo[i + 1], yo[i + 1]), (xo[i], yo[i])]
        for i in range(nseg)
    ]
    colors = cmap((np.arange(nseg) + 0.5) / nseg)
    # edgecolor == facecolor kills white hairline seams in PDF output
    ax.add_collection(
        PolyCollection(
            verts, facecolors=colors, edgecolors=colors, linewidths=1, zorder=5
        )
    )
    ax.plot(
        np.r_[xi, xo[::-1], xi[:1]],
        np.r_[yi, yo[::-1], yi[:1]],
        color=edge_color,
        lw=1,
        zorder=6,
    )

    if ticks is None:
        ticks = np.linspace(vmin, vmax, 5)
    va = "bottom" if top else "top"
    for value in ticks:
        fraction = (value - vmin) / (vmax - vmin)
        tt = t0 + fraction * (t1 - t0)
        ct, st = np.cos(tt), np.sin(tt)
        ax.plot(
            [2 * r_out * ct, 2 * (r_out + 0.015) * ct],
            [r_out * st, (r_out + 0.015) * st],
            color=edge_color,
            lw=1,
            zorder=6,
        )
        angle = np.degrees(np.arctan2(-ct, 2 * st))  # local tangent, reads L->R
        angle = angle - 180 if angle > 90 else (angle + 180 if angle < -90 else angle)
        ax.text(
            2 * (r_out + 0.03) * ct,
            (r_out + 0.03) * st,
            f"{value:g}",
            rotation=angle,
            rotation_mode="anchor",
            ha="center",
            va=va,
            fontsize=fontsize,
            color=text_color,
            zorder=6,
        )

    if label:
        ylab = (r_out + 0.135) if top else -(r_out + 0.135)
        ax.text(
            0.0,
            ylab,
            label,
            ha="center",
            va=va,
            fontsize=fontsize + 1,
            color=text_color,
            zorder=6,
        )

    y0, y1 = ax.get_ylim()
    if top:
        ax.set_ylim(min(y0, -1.05), max(y1, r_out + 0.24))
    else:
        ax.set_ylim(min(y0, -(r_out + 0.24)), max(y1, 1.05))
    x0, x1 = ax.get_xlim()
    ax.set_xlim(min(x0, -2.05), max(x1, 2.05))


def _decorate_skymap(ax, display_grat, foreign_grat, label_coord, *, fontsize=9):
    """Graticules, meridian/parallel labels, and the FoV-transit colorbar."""
    import healpy as hp

    hp.visufunc.graticule(
        coord=foreign_grat,
        c="silver",
        linestyle="solid",
        lw=0.3,
        dpar=30,
        dmer=30,
        alpha=0.5,
    )
    hp.visufunc.graticule(
        coord=display_grat, c="w", linestyle="dashed", lw=0.4, dpar=30, dmer=30
    )
    for lat in [-90, -60, -30, 30, 60]:
        hp.visufunc.projtext(
            0,
            lat,
            rf"{lat}$^\circ$",
            lonlat=True,
            coord=label_coord,
            fontweight="bold",
            fontsize=fontsize,
            color="silver",
            ha="left",
            va="bottom",
        )
    for lon in [-150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150]:
        hp.visufunc.projtext(
            lon % 360,
            0,
            rf"{lon}$^\circ$",
            lonlat=True,
            coord=label_coord,
            fontweight="bold",
            fontsize=fontsize,
            color="silver",
            ha="left",
            va="bottom",
        )
    ax.text(
        -2.0,
        0.0,
        r"180$^\circ$",
        fontweight="bold",
        ha="left",
        va="bottom",
        fontsize=fontsize,
        color="silver",
    )
    ax.text(
        2.005,
        0.0,
        r"-180$^\circ$",
        fontweight="bold",
        ha="left",
        va="bottom",
        fontsize=fontsize,
        color="silver",
    )

    image = ax.get_images()[0]
    vmin, vmax = image.get_clim()
    add_curved_colorbar(
        ax,
        vmin,
        vmax,
        "bone",
        side="top",
        ticks=[0, 100, 200],
        label="number of FoV transits",
        fontsize=18,
    )


def plot_star_sky_scanlaw():
    """Parent sample on the sky over the GOST DR4 FoV-transit map.

    One panel per display frame: colour is distance, marker area scales with
    stellar mass, and the two curved colorbars hug the ellipse (transits on
    top, distance on the bottom). The map is stored in equatorial coordinates;
    only the display frame changes between panels.
    """
    import healpy as hp
    from matplotlib.colors import Normalize, LinearSegmentedColormap
    from matplotlib.lines import Line2D

    gost_path = C.GOST_FOV_MAP
    if not gost_path.exists():
        print(f"  skipping star_sky_scanlaw: {gost_path} not found")
        return []

    # five columns of a 117-column, multi-GB CSV at 4M stars
    stars = pd.read_csv(
        C.stars_csv(),
        low_memory=False,
        usecols=["ra", "dec", "parallax", "mass_interp", "sig_AL"],
    )
    # the final parent sample: finite astrometry, positive parallax/mass, and a
    # usable noise model
    sky = stars.loc[
        np.isfinite(stars["ra"])
        & np.isfinite(stars["dec"])
        & np.isfinite(stars["parallax"])
        & (stars["parallax"] > 0)
        & np.isfinite(stars["mass_interp"])
        & (stars["mass_interp"] > 0)
        & stars["sig_AL"].notna()
    ].copy()
    sky["distance_pc"] = 1000.0 / sky["parallax"]
    print(f"  {len(sky):,} stars in the parent sample")

    transit_map = hp.read_map(str(gost_path))

    def marker_area(mass):
        return C.MASS_MARKER_FLOOR + C.MASS_MARKER_SCALE * np.asarray(mass)

    plasma = plt.get_cmap("plasma")
    # clip plasma's darkest end so nearby stars stay visible on dark map pixels
    star_cmap = LinearSegmentedColormap.from_list(
        "plasma_clipped", plasma(np.linspace(C.STAR_CMAP_CLIP, 1.0, 256))
    )
    star_norm = Normalize(vmin=0.0, vmax=C.DISTANCE_VMAX_PC)

    written = []
    for frame in C.SKY_FRAMES:
        if frame == "equatorial":
            mollview_coord, display_grat, foreign_grat, label_coord = (
                "C",
                "Equatorial",
                "Ecliptic",
                "C",
            )
        else:
            mollview_coord, display_grat, foreign_grat, label_coord = (
                ["C", "E"],
                "Ecliptic",
                "Equatorial",
                "E",
            )

        fig = plt.figure(figsize=C.SKYMAP_FIGSIZE)
        hp.visufunc.mollview(
            transit_map,
            fig=fig.number,
            coord=mollview_coord,
            title="",
            cbar=False,
            cmap="bone",
            notext=True,
            min=C.TRANSIT_VMIN,
            max=C.TRANSIT_VMAX,
            badcolor="white",
            bgcolor="white",
            flip="astro",
        )
        ax = plt.gca()

        # rasterized: at 4M stars a vector scatter is a PDF no viewer opens
        hp.visufunc.projscatter(
            sky["ra"].to_numpy(),
            sky["dec"].to_numpy(),
            lonlat=True,
            coord="C",
            c=sky["distance_pc"].to_numpy(),
            s=marker_area(sky["mass_interp"].to_numpy()),
            cmap=star_cmap,
            norm=star_norm,
            edgecolors="k",
            linewidths=0.12,
            alpha=0.88,
            zorder=10,
            rasterized=True,
        )

        _decorate_skymap(ax, display_grat, foreign_grat, label_coord)
        add_curved_colorbar(
            ax,
            0,
            C.DISTANCE_VMAX_PC,
            star_cmap,
            side="bottom",
            ticks=[0, 50, 100, 150, 200, 250],
            label="distance [pc]",
            fontsize=18,
        )

        handles = [
            Line2D(
                [],
                [],
                marker="o",
                linestyle="none",
                markerfacecolor="0.3",
                markeredgecolor="k",
                markeredgewidth=0.2,
                markersize=np.sqrt(marker_area(mass)),
                label=rf"{mass:g} $M_\odot$",
            )
            for mass in C.MASS_LEGEND_MSUN
        ]
        ax.legend(
            handles=handles,
            title="stellar mass",
            loc="center left",
            bbox_to_anchor=(1.01, 0.5),
            frameon=True,
            fontsize=13,
            title_fontsize=18,
        )

        written += _save(fig, f"star_sky_scanlaw_{frame}")
    return written


# ==========================================================================
# 2. Population schematic
# ==========================================================================
def plot_population_schematic():
    """Selection funnel (G23H -> parent) and the population branching.

    Every number and the prior annotation are read from the configuration and
    the catalogs on disk, so the schematic always describes the run that
    produced them.
    """
    import pyarrow as pa
    import pyarrow.ipc as ipc
    from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle

    ink = C.INK_COLOR
    points = 1 / 66.0  # ~data units per point at this figure scale

    def box(
        ax,
        cx,
        cy,
        w,
        h,
        facecolor,
        title,
        lines=None,
        textcolor=ink,
        fontsize=10.0,
        title_fs=12.0,
        edgecolor="none",
        lw=1.4,
    ):
        """Rounded box whose title+body block is truly vertically centred."""
        x, y = cx - w / 2, cy - h / 2
        ax.add_patch(
            FancyBboxPatch(
                (x, y),
                w,
                h,
                boxstyle="round,pad=0.02,rounding_size=0.10",
                linewidth=lw,
                facecolor=facecolor,
                edgecolor=edgecolor,
                zorder=3,
            )
        )
        if lines:
            gap, title_h = 0.16, title_fs * points
            top0 = cy + h / 2.0
            t_title = ax.text(
                cx,
                top0,
                title,
                ha="center",
                va="top",
                fontsize=title_fs,
                fontweight="bold",
                color=textcolor,
                zorder=4,
            )
            t_body = ax.text(
                cx,
                top0 - title_h - gap,
                "\n".join(lines),
                ha="center",
                va="top",
                fontsize=fontsize,
                color=textcolor,
                zorder=4,
                linespacing=1.45,
            )
            # measure the rendered extent and shift so the block centres on cy
            fig = ax.figure
            fig.canvas.draw()
            renderer = fig.canvas.get_renderer()
            inverse = ax.transData.inverted()

            def yspan(text):
                bb = text.get_window_extent(renderer)
                (_, ylo), (_, yhi) = inverse.transform([(bb.x0, bb.y0), (bb.x0, bb.y1)])
                return ylo, yhi

            tlo, thi = yspan(t_title)
            blo, bhi = yspan(t_body)
            dy = cy - 0.5 * (max(thi, bhi) + min(tlo, blo))
            t_title.set_y(top0 + dy)
            t_body.set_y(top0 - title_h - gap + dy)
        else:
            ax.text(
                cx,
                cy,
                title,
                ha="center",
                va="center",
                fontsize=title_fs,
                fontweight="bold",
                color=textcolor,
                zorder=4,
            )
        return {"L": (x, cy), "R": (x + w, cy), "T": (cx, y + h), "B": (cx, y)}

    def arrow(ax, p0, p1, color=ink, lw=1.9, rad=0.0):
        ax.add_patch(
            FancyArrowPatch(
                p0,
                p1,
                arrowstyle="-|>",
                mutation_scale=15,
                lw=lw,
                color=color,
                connectionstyle=f"arc3,rad={rad}",
                zorder=1,
                shrinkA=2,
                shrinkB=3,
            )
        )

    # ---- counts, straight from the inputs and the generated catalogs ----
    with pa.memory_map(str(C.g23h_sample()), "r") as handle:
        n_g23h = ipc.open_file(handle).read_all().num_rows
    stars = pd.read_csv(C.stars_csv(), usecols=["sig_AL"])
    n_after_pecaut = len(stars)
    n_parent = int(np.isfinite(stars["sig_AL"]).sum())
    drop_pecaut = n_g23h - n_after_pecaut
    drop_sigal = n_after_pecaut - n_parent

    def resonant(frame):
        n = int(frame["near_resonance"].sum())
        return n, 100.0 * n / len(frame)

    one, one_snr = read_population("1_companion"), read_population("1_companion", True)
    two, two_snr = read_population("2_companion"), read_population("2_companion", True)
    n_a1, n_d1, n_a2, n_d2 = len(one), len(one_snr), len(two), len(two_snr)
    drop_d1, drop_d2 = n_a1 - n_d1, n_a2 - n_d2
    n_res_a2, frac_res_a2 = resonant(two)
    n_res_d2, frac_res_d2 = resonant(two_snr)

    print(
        f"  funnel: G23H {n_g23h:,} -> Pecaut {n_after_pecaut:,} (-{drop_pecaut}) "
        f"-> parent {n_parent:,} (-{drop_sigal})"
    )
    print(
        f"  pops  : control {n_parent:,} | 1c {n_a1:,}/{n_d1:,} (-{drop_d1}) "
        f"| 2c {n_a2:,}/{n_d2:,} (-{drop_d2})"
    )

    fig, ax = plt.subplots(figsize=(14.0, 14.0 / 1.759))
    ax.set_xlim(0.1, 15.4)
    ax.set_ylim(0.3, 9.0)
    ax.set_aspect("equal")
    ax.axis("off")

    # bands group by companion count, not by selection regime
    band = "#ECEFF3"
    ax.add_patch(Rectangle((0.75, 0.95), 3.00, 3.35, facecolor=band, zorder=0))
    ax.add_patch(Rectangle((3.85, 0.95), 5.75, 3.35, facecolor=band, zorder=0))
    ax.add_patch(Rectangle((9.70, 0.95), 5.75, 3.35, facecolor=band, zorder=0))
    for x, text in [
        (2.25, "zero companions"),
        (6.72, "one companion"),
        (12.57, "two companions"),
    ]:
        ax.text(
            x,
            4.02,
            text,
            ha="center",
            va="center",
            fontsize=24,
            fontweight="bold",
            color=ink,
        )

    # ---- top: the horizontal selection funnel ----
    col_funnel, col_parent = C.FUNNEL_COLOR, C.PARENT_COLOR
    g = box(
        ax,
        2.60,
        7.85,
        2.95,
        1.45,
        col_funnel,
        r"$\mathtt{G23H}$ catalog",
        [r"DR2-DR3 cross-match", r"$G<16$"],
        title_fs=23,
        fontsize=15,
    )
    b1 = box(
        ax,
        5.90,
        7.85,
        3.05,
        1.55,
        col_funnel,
        f"{n_g23h:,} stars",
        [r"$\varpi\geq4$ mas ($d\leq250$ pc);", "uniform-in-distance draw"],
        title_fs=23,
        fontsize=15,
    )
    b2 = box(
        ax,
        9.20,
        7.85,
        2.95,
        1.35,
        col_funnel,
        f"{n_after_pecaut:,} stars",
        [rf"$-{drop_pecaut}$: brighter than P\&M13"],
        title_fs=23,
        fontsize=15,
    )
    parent = box(
        ax,
        12.50,
        7.85,
        3.05,
        1.55,
        col_parent,
        "parent sample",
        [rf"$-{drop_sigal}$: no $\sigma_{{\rm AL}}$ (DR3)", f"n = {n_parent:,}"],
        title_fs=27,
        fontsize=16,
    )

    for start, end in [(g["R"], b1["L"]), (b1["R"], b2["L"]), (b2["R"], parent["L"])]:
        arrow(ax, start, end, color=col_funnel, lw=2.8)

    # prior annotation, written out of the configured priors
    mass_min_mars = C.MASS_MIN_MJUP / C.MARS_MASS_MJUP
    ax.text(
        12.5,
        6.3,
        "per-companion priors:\n"
        rf"$M_p\in[{mass_min_mars:.3g}\,M_{{\rm Mars}},\,"
        rf"{C.MASS_MAX_MJUP:g}\,M_{{\rm Jup}}]$ log-uniform"
        "\n"
        rf"$a\in[{C.A_MIN_AU:g},{C.A_MAX_AU:g}]$ au log-uniform"
        "\n"
        rf"$e\sim\mathcal{{U}}({C.ECC_MIN:g},{C.ECC_MAX:g})$; "
        r"isotropic angles",
        ha="center",
        va="center",
        fontsize=15,
        color=ink,
        linespacing=1.5,
        bbox=dict(boxstyle="round,pad=0.5", fc="white", ec=col_parent, lw=1.2),
    )

    # ---- bottom: control + the one/two-companion groups ----
    width, height, y_box = 2.80, 2.55, 2.35
    # the high-SNR populations are selected after generation, not drawn
    snr_line = (
        rf"$\mathrm{{SNR_{{tot}}}}\geq{C.HIGH_SNR_MIN:g}$ "
        r"on every companion"
    )
    ctrl = box(
        ax,
        2.25,
        y_box,
        width,
        height,
        C.CONTROL_COLOR,
        "control",
        [f"n = {n_parent:,}"],
        title_fs=27,
        fontsize=16,
    )
    a1 = box(
        ax,
        5.30,
        y_box,
        width,
        height,
        C.SCHEMATIC_RANDOM_COLOR,
        "random",
        [f"n = {n_a1:,}"],
        title_fs=27,
        fontsize=16,
    )
    d1 = box(
        ax,
        8.10,
        y_box,
        width,
        height,
        C.SCHEMATIC_HIGH_SNR_COLOR,
        "high-SNR",
        [snr_line, r"selected, not drawn", f"n = {n_d1:,}"],
        title_fs=27,
        fontsize=16,
    )
    a2 = box(
        ax,
        11.15,
        y_box,
        width,
        height,
        C.SCHEMATIC_RANDOM_COLOR,
        "random",
        [
            r"hill-stable",
            rf"{n_res_a2} resonant ({frac_res_a2:.1f}\%)",
            f"n = {n_a2:,}",
        ],
        title_fs=27,
        fontsize=16,
    )
    d2_lines = [
        r"hill-stable",
        rf"{n_res_d2} resonant ({frac_res_d2:.1f}\%)",
        snr_line,
        r"selected, not drawn",
        f"n = {n_d2:,}",
    ]
    d2 = box(
        ax,
        13.95,
        y_box,
        width,
        height,
        C.SCHEMATIC_HIGH_SNR_COLOR,
        "high-SNR",
        d2_lines,
        title_fs=27,
        fontsize=16,
    )

    # parent fans out to each population, stopping at the band headers
    header_y = 4.30
    for target, color, rad in [
        (ctrl, "#5A6B7B", 0.20),
        (a1, C.RANDOM_COLOR, 0.13),
        (d1, C.HIGH_SNR_COLOR, 0.07),
        (a2, C.RANDOM_COLOR, -0.01),
        (d2, C.HIGH_SNR_COLOR, -0.10),
    ]:
        arrow(ax, parent["B"], (target["T"][0], header_y), color=color, lw=2.8, rad=rad)

    coplanar_pct = 100 * C.COPLANAR_PROBABILITY
    ax.text(
        12.57,
        0.60,
        rf"{coplanar_pct:.0f}/{100 - coplanar_pct:.0f} coplanar vs. "
        r"mutually inclined; $a_1<a_2$",
        ha="center",
        va="center",
        fontsize=15,
        color=ink,
        style="italic",
    )
    ax.set_title(
        r"the $\mathtt{epochalypse}$ injected populations",
        fontsize=45,
        fontweight="bold",
        pad=4,
    )
    fig.tight_layout()
    return _save(fig, "population_schematic")


# ==========================================================================
# 3. Prior diagnostics, one panel grid per companion count
# ==========================================================================
def plot_population_diagnostics(n_companions):
    """Overlaid prior distributions for the random and high-SNR populations."""
    from matplotlib.patches import Patch

    population = f"{n_companions}_companion"
    random = read_population(population)
    high_snr = read_population(population, high_snr=True)

    random_color, snr_color = C.RANDOM_COLOR, C.HIGH_SNR_COLOR

    def overlay(ax, left, right, bins=60):
        """Overlay two densities on shared bin edges."""
        left, right = np.asarray(left), np.asarray(right)
        finite = np.concatenate([left[np.isfinite(left)], right[np.isfinite(right)]])
        edges = np.histogram_bin_edges(finite, bins=bins)
        for values, color in [(left, random_color), (right, snr_color)]:
            ax.hist(
                values,
                bins=edges,
                density=True,
                histtype="stepfilled",
                color=color,
                edgecolor=color,
                linewidth=1.3,
                alpha=0.25,
            )

    def style(axes):
        for ax in np.asarray(axes).flat:
            ax.grid(axis="y", alpha=0.18, linewidth=0.7)
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            ax.tick_params(width=1.1, length=5)
            ax.margins(x=0.02)

    handles = [
        Patch(
            facecolor=random_color,
            edgecolor=random_color,
            alpha=0.40,
            linewidth=1.3,
            label=rf"random ($N={len(random):,}$)",
        ),
        Patch(
            facecolor=snr_color,
            edgecolor=snr_color,
            alpha=0.40,
            linewidth=1.3,
            label=rf"high-SNR ($N={len(high_snr):,}$)",
        ),
    ]
    cos_bins = np.linspace(-1, 1, 50)

    with plt.rc_context(
        {
            "axes.titlesize": 40,
            "axes.labelsize": 40,
            "xtick.labelsize": 34,
            "ytick.labelsize": 34,
            "legend.fontsize": 36,
            "axes.linewidth": 1.2,
        }
    ):
        if n_companions == 2:
            fig, axes = plt.subplots(3, 3, figsize=(15, 13.5))

            overlay(axes[0, 0], random["sma_1"], high_snr["sma_1"])
            axes[0, 0].set(xlabel=r"$a_1$ [AU]", title=r"inner semimajor axis")
            overlay(axes[0, 1], random["sma_2"], high_snr["sma_2"])
            axes[0, 1].set(xlabel=r"$a_2$ [AU]", title=r"outer semimajor axis")

            overlay(
                axes[0, 2], np.log10(random["P_ratio"]), np.log10(high_snr["P_ratio"])
            )
            axes[0, 2].set(xlabel=r"$\log_{10}(P_2/P_1)$", title=r"period ratio")
            axes[0, 2].set_ylim(top=axes[0, 2].get_ylim()[1] * 1.15)
            # mark the first-order MMRs the resonant systems cluster at
            for j, sign in zip(C.RESONANCE_ORDERS, (+1, -1)):
                ratio = (j + 1) / j
                x = np.log10(ratio)
                axes[0, 2].axvline(x, color="0.30", ls="--", lw=1.5)
                axes[0, 2].annotate(
                    rf"{j + 1}:{j}",
                    xy=(x, 0.62),
                    xycoords=("data", "axes fraction"),
                    xytext=(7 * sign, 0),
                    textcoords="offset points",
                    rotation=90,
                    rotation_mode="anchor",
                    ha="left" if sign > 0 else "right",
                    va="center",
                    fontsize=26,
                    color="0.30",
                )

            overlay(
                axes[1, 0],
                np.log10(random["mass_pl_1"]),
                np.log10(high_snr["mass_pl_1"]),
            )
            axes[1, 0].set(
                xlabel=r"$\log_{10}(M_{\mathrm{p},1})$ [$M_{\mathrm{Jup}}$]",
                title=r"inner planet mass",
            )
            overlay(
                axes[1, 1],
                np.log10(random["mass_pl_2"]),
                np.log10(high_snr["mass_pl_2"]),
            )
            axes[1, 1].set(
                xlabel=r"$\log_{10}(M_{\mathrm{p},2})$ [$M_{\mathrm{Jup}}$]",
                title=r"outer planet mass",
            )
            overlay(
                axes[1, 2],
                np.cos(np.radians(random["inc_1"])),
                np.cos(np.radians(high_snr["inc_1"])),
                bins=cos_bins,
            )
            axes[1, 2].set(xlabel=r"$\cos(i_1)$", title=r"inclination")

            overlay(axes[2, 0], random["ecc_1"], high_snr["ecc_1"], bins=50)
            axes[2, 0].set(xlabel=r"$e_1$", title=r"inner eccentricity")
            overlay(axes[2, 1], random["ecc_2"], high_snr["ecc_2"], bins=50)
            axes[2, 1].set(xlabel=r"$e_2$", title=r"outer eccentricity")

            def mutual_inclination(frame):
                """cos i_mut = cos i1 cos i2 + sin i1 sin i2 cos(Omega1 - Omega2)."""
                i1 = np.radians(frame["inc_1"].to_numpy())
                i2 = np.radians(frame["inc_2"].to_numpy())
                dnode = np.radians(
                    frame["Omega_1"].to_numpy() - frame["Omega_2"].to_numpy()
                )
                cos_mutual = np.cos(i1) * np.cos(i2) + np.sin(i1) * np.sin(i2) * np.cos(
                    dnode
                )
                return np.degrees(np.arccos(np.clip(cos_mutual, -1.0, 1.0)))

            # coplanar systems sit at i_mut = 0 by construction and would swamp
            # the panel, so only the non-coplanar half is shown
            overlay(
                axes[2, 2],
                mutual_inclination(random[~random["coplanar"].astype(bool)]),
                mutual_inclination(high_snr[~high_snr["coplanar"].astype(bool)]),
            )
            axes[2, 2].set(
                xlabel=r"$i_{\mathrm{mut}}$ [deg]", title=r"mutual inclination"
            )
            axes[2, 2].set_ylim(top=axes[2, 2].get_ylim()[1] * 1.22)
            axes[2, 2].text(
                0.5,
                0.95,
                r"non-coplanar half",
                transform=axes[2, 2].transAxes,
                ha="center",
                va="top",
                fontsize=27,
                color="0.25",
            )

            title = r"$\mathtt{epochalypse}$ injected two companion systems"
            rect_top, sup_y = 0.915, 0.99
        else:
            fig, axes = plt.subplots(2, 3, figsize=(15, 10.5))

            overlay(axes[0, 0], random["sma"], high_snr["sma"])
            axes[0, 0].set(xlabel=r"$a$ [AU]", title=r"semimajor axis")
            overlay(axes[0, 1], random["mass_st"], high_snr["mass_st"])
            axes[0, 1].set(xlabel=r"$M_\star$ [$M_\odot$]", title=r"stellar mass")
            overlay(
                axes[0, 2], np.log10(random["mass_pl"]), np.log10(high_snr["mass_pl"])
            )
            axes[0, 2].set(
                xlabel=r"$\log_{10}(M_{\mathrm{p}})$ [$M_{\mathrm{Jup}}$]",
                title=r"planet mass",
            )

            overlay(
                axes[1, 0], np.log10(random["period"]), np.log10(high_snr["period"])
            )
            axes[1, 0].set(xlabel=r"$\log_{10}(P)$ [yr]", title=r"orbital period")
            baseline = C.BASELINE_YEARS
            axes[1, 0].axvline(np.log10(baseline), color="0.25", ls=":", lw=3)
            axes[1, 0].annotate(
                r"DR4 baseline",
                xy=(np.log10(baseline) - 0.05, 0.04),
                xycoords=("data", "axes fraction"),
                xytext=(6, 0),
                textcoords="offset points",
                rotation=90,
                rotation_mode="anchor",
                ha="left",
                va="bottom",
                fontsize=24,
                color="0.25",
            )

            overlay(axes[1, 1], random["ecc"], high_snr["ecc"], bins=50)
            axes[1, 1].set(xlabel=r"$e$", title=r"eccentricity")
            overlay(
                axes[1, 2],
                np.cos(np.radians(random["inc"])),
                np.cos(np.radians(high_snr["inc"])),
                bins=cos_bins,
            )
            axes[1, 2].set(xlabel=r"$\cos(i)$", title=r"inclination")

            title = r"$\mathtt{epochalypse}$ injected one companion systems"
            rect_top, sup_y = 0.875, 0.985

        style(axes)
        for ax in axes[:, 0]:
            ax.set_ylabel("density")

        fig.tight_layout(rect=[0, 0, 1, rect_top])
        suptitle = fig.suptitle(title, fontsize=50, y=sup_y)

        # centre the shared legend in the gap between panel titles and suptitle
        fig.canvas.draw()
        renderer = fig.canvas.get_renderer()
        inverse = fig.transFigure.inverted()
        title_top = max(
            inverse.transform((0, ax.title.get_window_extent(renderer).ymax))[1]
            for ax in axes[0, :]
        )
        sup_bottom = inverse.transform((0, suptitle.get_window_extent(renderer).ymin))[
            1
        ]
        fig.legend(
            handles=handles,
            loc="center",
            ncol=2,
            bbox_to_anchor=(0.5, 0.5 * (title_top + sup_bottom)),
            frameon=False,
            fontsize=36,
            handlelength=1.7,
            handleheight=1.2,
            columnspacing=2.4,
        )

    return _save(fig, f"pop_diagnostics_{n_companions}planet")


# ==========================================================================
# 4. Gallery of injected orbits
# ==========================================================================
def orbit_points_au(a, e, inc, node, argument, n=500):
    """On-sky Keplerian ellipse in AU, following Hilditch (2004)."""
    argument, node, inc = np.radians(argument), np.radians(node), np.radians(inc)
    A = a * (
        np.cos(argument) * np.cos(node) - np.sin(argument) * np.sin(node) * np.cos(inc)
    )
    B = a * (
        np.cos(argument) * np.sin(node) + np.sin(argument) * np.cos(node) * np.cos(inc)
    )
    F = a * (
        -np.sin(argument) * np.cos(node) - np.cos(argument) * np.sin(node) * np.cos(inc)
    )
    G = a * (
        -np.sin(argument) * np.sin(node) + np.cos(argument) * np.cos(node) * np.cos(inc)
    )
    eccentric_anomaly = np.linspace(0, 2 * np.pi, n)
    X = np.cos(eccentric_anomaly) - e
    Y = np.sqrt(1 - e**2) * np.sin(eccentric_anomaly)
    return B * X + G * Y, A * X + F * Y


def plot_companion_gallery():
    """One row per companion population, each showing sample on-sky orbits."""
    from matplotlib.lines import Line2D

    inner_color, outer_color = C.INNER_COLOR, C.OUTER_COLOR
    n_per_row = C.GALLERY_N_PER_ROW

    panels = [
        (name, high_snr, "\n".join(label.split(", ")))
        for name, high_snr, label in C.PANELS
    ]

    def compact(value):
        """No scientific notation, ~2 significant figures."""
        value = float(value)
        if value >= 10:
            return f"{value:.0f}"
        return f"{value:.1f}" if value >= 1 else f"{value:.2g}"

    fig, axes = plt.subplots(
        len(panels),
        n_per_row,
        figsize=(n_per_row * 2.05, len(panels) * 2.55),
        squeeze=False,
    )

    for row, (name, high_snr, label) in enumerate(panels):
        frame = read_population(name, high_snr)
        sample = frame.sample(
            min(n_per_row, len(frame)), random_state=C.GALLERY_SEED
        ).reset_index(drop=True)

        for column in range(n_per_row):
            ax = axes[row, column]
            ax.set_xticks([])
            ax.set_yticks([])
            for spine in ax.spines.values():
                spine.set_color("0.7")
            if column >= len(sample):
                ax.axis("off")
                continue

            system = sample.iloc[column]
            if C.POPULATIONS[name] == 1:
                x, y = orbit_points_au(
                    system["sma"],
                    system["ecc"],
                    system["inc"],
                    system["Omega"],
                    system["omega"],
                )
                ax.plot(x, y, lw=3, color=inner_color)
                title = (
                    rf"$M={compact(system['mass_pl'])}$"
                    "\n"
                    rf"$P={compact(system['period'])}$"
                    "\n"
                    rf"$e={system['ecc']:.2f}$"
                    "\n"
                    rf"$i={system['inc']:.0f}$"
                )
            else:
                for suffix, color in [("_1", inner_color), ("_2", outer_color)]:
                    x, y = orbit_points_au(
                        system[f"sma{suffix}"],
                        system[f"ecc{suffix}"],
                        system[f"inc{suffix}"],
                        system[f"Omega{suffix}"],
                        system[f"omega{suffix}"],
                    )
                    ax.plot(x, y, lw=3, color=color)
                title = (
                    rf"$M=[{compact(system['mass_pl_1'])},"
                    rf"{compact(system['mass_pl_2'])}]$"
                    "\n"
                    rf"$P=[{compact(system['period_1'])},"
                    rf"{compact(system['period_2'])}]$"
                    "\n"
                    rf"$e=[{system['ecc_1']:.2f},{system['ecc_2']:.2f}]$"
                    "\n"
                    rf"$i=[{system['inc_1']:.0f},{system['inc_2']:.0f}]$"
                )

            ax.plot(
                0,
                0,
                marker="*",
                color="k",
                ms=9,
                markeredgecolor="k",
                markeredgewidth=0.6,
                zorder=5,
            )
            ax.set_aspect("equal", adjustable="datalim")
            ax.set_title(title, fontsize=16, linespacing=1.2)

        axes[row, 0].set_ylabel(label, fontsize=19, labelpad=10, linespacing=1.15)

    handles = [
        Line2D([0], [0], color=inner_color, lw=2.5, label="inner companion"),
        Line2D([0], [0], color=outer_color, lw=2.5, label="outer companion"),
        Line2D(
            [0],
            [0],
            marker="*",
            color="k",
            lw=0,
            markersize=14,
            markeredgecolor="k",
            markeredgewidth=0.5,
            label="host star",
        ),
    ]
    fig.legend(
        handles=handles,
        loc="upper center",
        ncol=3,
        frameon=False,
        fontsize=24,
        bbox_to_anchor=(0.5, 0.955),
        columnspacing=2.4,
    )
    fig.suptitle(
        rf"{len(panels) * n_per_row} $\mathtt{{epochalypse}}$ injected "
        r"companion systems (on-sky orbits)",
        fontsize=45,
        y=0.992,
    )
    fig.text(
        0.5,
        0.016,
        r"per panel:\ \ $M$ [$M_{\rm J}$]\quad $P$ [yr]\quad $e$\quad "
        r"$i$ [deg];\ \ listed as [inner, outer]",
        ha="center",
        va="bottom",
        fontsize=22,
        color="0.30",
    )
    fig.tight_layout(rect=[0, 0.045, 1, 0.925])
    return _save(fig, "companion_gallery")


# ==========================================================================
# 5. Mass vs. period, coloured by astrometric signature
# ==========================================================================
def plot_simulated_planet_mass_period():
    """Companion mass against period for each population, coloured by the
    stellar reflex semimajor axis alpha."""
    from matplotlib.colors import LogNorm, LinearSegmentedColormap
    from matplotlib.lines import Line2D

    # panel order: one/two random on the top row, one/two high-SNR below
    cmap = plt.get_cmap("rainbow")
    cmap = LinearSegmentedColormap.from_list(
        "rainbow_trunc", cmap(np.linspace(0, 1, 256))
    )

    frames, signatures = [], []
    for name, high_snr, label in C.PANELS:
        frame = read_population(name, high_snr)
        # alpha is recorded per companion at generation time, so it is read
        # rather than recomputed here
        if C.POPULATIONS[name] == 1:
            signatures.append(frame["alpha_mas"].to_numpy())
        else:
            for index in [1, 2]:
                signatures.append(frame[f"alpha_{index}_mas"].to_numpy())
        frames.append((name, label, frame))

    signatures = np.concatenate(signatures)
    signatures = signatures[np.isfinite(signatures) & (signatures > 0)]
    norm = LogNorm(
        vmin=np.quantile(signatures, 0.01), vmax=np.quantile(signatures, 0.99)
    )

    fig, axes = plt.subplots(2, 2, figsize=(14, 10), sharex=True, sharey=True)
    # constrained_layout would silently override the explicit adjust below
    if hasattr(fig, "set_layout_engine"):
        fig.set_layout_engine("none")

    scatter = None
    for ax, (name, label, frame) in zip(axes.flat, frames):
        if C.POPULATIONS[name] == 1:
            scatter = ax.scatter(
                frame["period"],
                frame["mass_pl"],
                c=frame["alpha_mas"],
                norm=norm,
                cmap=cmap,
                s=27,
                alpha=0.65,
                linewidths=0,
                rasterized=True,
            )
        else:
            scatter = ax.scatter(
                frame["period_1"],
                frame["mass_pl_1"],
                c=frame["alpha_1_mas"],
                norm=norm,
                cmap=cmap,
                marker="o",
                s=27,
                alpha=0.7,
                linewidths=0,
                rasterized=True,
            )
            ax.scatter(
                frame["period_2"],
                frame["mass_pl_2"],
                c=frame["alpha_2_mas"],
                norm=norm,
                cmap=cmap,
                marker="^",
                s=36,
                alpha=0.7,
                linewidths=0,
                rasterized=True,
            )

        ax.axvline(C.BASELINE_YEARS, color="k", ls="--", lw=2)
        ax.set_xscale("log")
        ax.set_yscale("log")
        # "one companion, random" -> "one companion: random"
        ax.set_title(label.replace(", ", ": "), pad=12, fontsize=27)
        ax.grid(True, which="both", alpha=0.15)
        ax.tick_params(which="both", labelsize=16)

    for ax in axes[-1, :]:
        ax.set_xlabel("orbital period [yr]", fontsize=23)
    for ax in axes[:, 0]:
        ax.set_ylabel(r"companion mass [$M_{\rm Jup}$]", fontsize=23)

    fig.subplots_adjust(
        left=0.075, right=0.88, top=0.85, bottom=0.085, hspace=0.17, wspace=0.06
    )
    cax = fig.add_axes([0.905, 0.085, 0.02, 0.775])
    colorbar = fig.colorbar(scatter, cax=cax, orientation="vertical", extend="both")
    colorbar.set_label(r"stellar reflex semimajor axis $\alpha$ [mas]", fontsize=24)
    colorbar.ax.tick_params(labelsize=16)

    # centre the title/legend over the panel block, not the whole figure
    centre_x = 0.5 * (0.075 + 0.88)
    fig.suptitle(
        r"$\mathtt{epochalypse}$ injected companions", fontsize=36, x=centre_x, y=0.965
    )
    handles = [
        Line2D(
            [0],
            [0],
            marker="o",
            color="0.35",
            lw=0,
            markersize=10,
            label="inner companion",
        ),
        Line2D(
            [0],
            [0],
            marker="^",
            color="0.35",
            lw=0,
            markersize=11,
            label="outer companion",
        ),
        Line2D([0], [0], color="k", ls="--", lw=2, label=r"\textit{Gaia} DR4 baseline"),
    ]
    fig.legend(
        handles=handles,
        loc="center",
        bbox_to_anchor=(centre_x, 0.905),
        ncol=3,
        frameon=False,
        fontsize=20,
        columnspacing=2.4,
        handlelength=1.8,
    )
    return _save(fig, "simulated_planets_mass_period")


# ==========================================================================
# Driver
# ==========================================================================
BUILDERS = {
    "star_sky_scanlaw": plot_star_sky_scanlaw,
    "population_schematic": plot_population_schematic,
    "pop_diagnostics_1planet": lambda: plot_population_diagnostics(1),
    "pop_diagnostics_2planet": lambda: plot_population_diagnostics(2),
    "companion_gallery": plot_companion_gallery,
    "simulated_planets_mass_period": plot_simulated_planet_mass_period,
}


def make_figures(names=None):
    """Build the requested catalog-generation figures.

    A figure whose inputs are missing is reported and skipped, so one absent
    population does not abort the rest of the set.
    """
    _apply_style()
    selected = list(names) if names else list(C.FIGURES)
    unknown = [name for name in selected if name not in BUILDERS]
    if unknown:
        raise KeyError(f"unknown figure(s): {unknown}; available: {sorted(BUILDERS)}")

    written = []
    for name in selected:
        print(f"\n[{name}]")
        try:
            written += BUILDERS[name]() or []
        except FileNotFoundError as error:
            print(f"  skipped: {error}")
    return written
